version: '3.8'
services:
  nginx:
    image: my_nginx_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"  # Expose port for the cache server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./images:/usr/share/nginx/html/images
      - ./script/purge_cache.sh:/var/cache/nginx/purge_cache.sh
      - /var/cache/nginx
    command: ["nginx", "-g", "daemon off;"]
