version: '3.8'
services:
  nginx:
    image: my_nginx_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"  # Expose port for the cache server
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./images:/usr/local/openresty/nginx/html/images
      - /var/cache/nginx
    command: ["openresty", "-g", "daemon off;"]
